env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/rport
builds:
  - id: rportcli
    main: ./
    binary: rportcli
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/cmd.Version={{.Version}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: amd64
      # TODO: remove when https://github.com/go-ole/go-ole/issues/202 will be fixed
      - goos: windows
        goarch: arm
archives:
  - id: rportcli
    builds:
      - rportcli
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: cloudradar-monitoring
    name: rportcli
  draft: true
  prerelease: true
